### PR TITLE
Update bolt repo to llvm now that it's merged

### PR DESCRIPTION
**Pull request by kmod**
And update to the latest commit

### CODE REVIEW

**Comment by undingen** [comment]
👍, when you update please also update our conda bolt recipe (and upload a new bolt conda package) because else the CI will keep on using the older bolt version.

**Comment by kmod** [comment]
Ok looks like CI passed, this is ready for review now

**Review by undingen — COMMENTED** [review]
already wanted to press merge but now I noticed the following:
I think the `build_num` in `pyston/conda/pyston/meta.yaml` needs to be incremented. Because the version number of the pyston package didn't get touched. (the bold package should be fine because it's version number changed).
I don't think we plan to release a new pyston package currently so it's theoretically only a problem...
Else looks good :)

**Comment by kmod** [comment]
Ah ok that's a good idea, I went ahead and did that

**Pull request merged**
